site_name: EasyAdmin
site_description: EasyAdmin Documentation

repo_url: https://github.com/Blumlaut/EasyAdmin
edit_uri: "edit/docs/docs/"

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences


plugins:
  - search
  - git-revision-date

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - search.highlight



nav:
    - "Index": 'index.md'
    - 'install.md'
    - 'Configuration':
        - 'config.md'
        - 'permissions.md'
        - 'admins.md'
    - 'Features':
        - 'commands.md'
        - 'webhook.md'
        - 'discord-screenshots.md'
        - 'reminders.md'
        - 'shortcuts.md'
        - 'backups.md'
    - 'updating.md'
    - 'troubleshooting.md'
    - 'Developer Reference':
        - 'api.md'
        - 'plugins.md'
    - 'translating.md'
  