site_name: EasyAdmin
site_description: EasyAdmin Documentation

repo_url: https://github.com/Blumlaut/EasyAdmin
edit_uri: ""


theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
nav:
    - "Index": 'index.md'
    - 'install.md'
