site_name: EasyAdmin
site_description: EasyAdmin Documentation

repo_url: https://github.com/Blumlaut/EasyAdmin
edit_uri: ""


theme:
  name: readthedocs


nav:
    - "Index": 'index.md'
    - 'install.md'
